# version: '3'
x-common-commands:
  node_entrypoint: &node_entrypoint >
    bash -c "
    ./start_node.sh
    "
services:
  node2:
    image: blockchain-node:geth-poa
    container_name: node2
    hostname: node2
    env_file:
      - domain2.env
    command: *node_entrypoint
    volumes:
      - "./config:/src/"
    network_mode: host
    restart: always

