# version: '3'
x-common-commands:
  node_entrypoint: &node_entrypoint >
    bash -c "
    ./start_node.sh
    "
services:
  bootnode:
    image: blockchain-node:geth-poa
    container_name: bootnode
    hostname: bootnode
    env_file:
      - bootnode.env
    command: *node_entrypoint
    ports:
      - "30301:30301" # DISC_PORT
    volumes:
      - "./config:/src/"
    restart: always

  node1:
    image: blockchain-node:geth-poa
    container_name: node1
    hostname: node1
    env_file:
      - domain1.env
    command: *node_entrypoint
    volumes:
      - "./config:/src/"
    depends_on:
      - bootnode
    ports:
      - "8545:8545"
      - "30303:30303"
    restart: always

  eth-netstats:
    image: eth-netstats
    container_name: eth-netstats
    ports:
      - "3000:3000"
    depends_on:
      - node1
    restart: always
