version: '3.8'
services:
  bootnode:
    image: dlt-node
    container_name: bootnode
    hostname: bootnode
    volumes:
      - ./docker-compose.env:/dlt-network/bootnode.env
      - ./scripts/password.txt:/dlt-network/password.txt
      - ./scripts/bootnode_start.sh:/dlt-network/bootnode_start.sh
    command: ./bootnode_start.sh
    networks:
      dlt_network:
        ipv4_address: ${BOOTNODE_IP}

  eth-netstats:
    image: eth-netstats
    container_name: eth-netstats
    ports:       
      - "3000:3000"
    depends_on:
      - node1
    networks:
      dlt_network:
        ipv4_address: ${ETH_NETSATS_IP}

  node1:
    image: dlt-node
    container_name: node1
    hostname: node1
    depends_on:
      - bootnode
    volumes:
      - ./docker-compose.env:/dlt-network/node1.env
      - ./scripts/genesis_10_validators.json:/dlt-network/genesis.json
      - ./scripts/password.txt:/dlt-network/password.txt
      - ./scripts/node1_start.sh:/dlt-network/node1_start.sh      
    command: ./node1_start.sh
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_1}

  node2:
    image: dlt-node
    container_name: node2
    hostname: node2
    depends_on:
      - bootnode
    volumes:
      - ./docker-compose.env:/dlt-network/node2.env
      - ./scripts/genesis_10_validators.json:/dlt-network/genesis.json
      - ./scripts/password.txt:/dlt-network/password.txt
      - ./scripts/node2_start.sh:/dlt-network/node2_start.sh      
    command: ./node2_start.sh
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_2}

  node3:
    image: dlt-node
    container_name: node3
    hostname: node3
    depends_on:
      - bootnode
    volumes:
      - ./docker-compose.env:/dlt-network/node3.env
      - ./scripts/genesis_10_validators.json:/dlt-network/genesis.json
      - ./scripts/password.txt:/dlt-network/password.txt
      - ./scripts/node3_start.sh:/dlt-network/node3_start.sh      
    command: ./node3_start.sh
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_3}

  node4:
    image: dlt-node
    container_name: node4
    hostname: node4
    depends_on:
      - bootnode
    volumes:
      - ./docker-compose.env:/dlt-network/node4.env
      - ./scripts/genesis_10_validators.json:/dlt-network/genesis.json
      - ./scripts/password.txt:/dlt-network/password.txt
      - ./scripts/node4_start.sh:/dlt-network/node4_start.sh      
    command: ./node4_start.sh
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_4}

  node5:
    image: dlt-node
    container_name: node5
    hostname: node5
    depends_on:
      - bootnode
    volumes:
      - ./docker-compose.env:/dlt-network/node5.env
      - ./scripts/genesis_10_validators.json:/dlt-network/genesis.json
      - ./scripts/password.txt:/dlt-network/password.txt
      - ./scripts/node5_start.sh:/dlt-network/node5_start.sh      
    command: ./node5_start.sh
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_5}

  node6:
    image: dlt-node
    container_name: node6
    hostname: node6
    depends_on:
      - bootnode
    volumes:
      - ./docker-compose.env:/dlt-network/node6.env
      - ./scripts/genesis_10_validators.json:/dlt-network/genesis.json
      - ./scripts/password.txt:/dlt-network/password.txt
      - ./scripts/node6_start.sh:/dlt-network/node6_start.sh      
    command: ./node6_start.sh
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_6}

  node7:
    image: dlt-node
    container_name: node7
    hostname: node7
    depends_on:
      - bootnode
    volumes:
      - ./docker-compose.env:/dlt-network/node7.env
      - ./scripts/genesis_10_validators.json:/dlt-network/genesis.json
      - ./scripts/password.txt:/dlt-network/password.txt
      - ./scripts/node7_start.sh:/dlt-network/node7_start.sh      
    command: ./node7_start.sh
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_7}

  node8:
    image: dlt-node
    container_name: node8
    hostname: node8
    depends_on:
      - bootnode
    volumes:
      - ./docker-compose.env:/dlt-network/node8.env
      - ./scripts/genesis_10_validators.json:/dlt-network/genesis.json
      - ./scripts/password.txt:/dlt-network/password.txt
      - ./scripts/node8_start.sh:/dlt-network/node8_start.sh      
    command: ./node8_start.sh
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_8}

  node9:
    image: dlt-node
    container_name: node9
    hostname: node9
    depends_on:
      - bootnode
    volumes:
      - ./docker-compose.env:/dlt-network/node9.env
      - ./scripts/genesis_10_validators.json:/dlt-network/genesis.json
      - ./scripts/password.txt:/dlt-network/password.txt
      - ./scripts/node9_start.sh:/dlt-network/node9_start.sh      
    command: ./node9_start.sh
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_9}


  node10:
    image: dlt-node
    container_name: node10
    hostname: node10
    depends_on:
      - bootnode
    volumes:
      - ./docker-compose.env:/dlt-network/node10.env
      - ./scripts/genesis_10_validators.json:/dlt-network/genesis.json
      - ./scripts/password.txt:/dlt-network/password.txt
      - ./scripts/node10_start.sh:/dlt-network/node10_start.sh      
    command: ./node10_start.sh
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_10}                                        
networks:
  dlt_network:
    name: dlt_network
    ipam:
      driver: default
      config: 
        - subnet: ${DLT_SUBNET}

        