---
apiVersion: v1
kind: NetworkOverlayConfig
metadata:
  name: federation-net
spec:
  network:
    protocol: VXLAN                 # overlay protocol
    vni: 200                        # VXLAN Network Identifier
    udpPort: 4747                   # UDP port for VXLAN encapsulation
    overlaySubnet: 172.20.50.0/24   # tenant/overlay subnet
  endpoints:                        # declare hosts by NAME                  
    - name: domain1-robot
    - name: domain1-edge
---
apiVersion: v1
kind: VtepNodeConfig
metadata:
  name: domain1-robot
spec:
  overlayRef: federation-net                # must match metadata.name above
  endpointRef: domain1-robot                # must match an endpoints.name above
  vtepIP: 10.3.202.67                       # underlay IP of this VTEP
  addressPool: "172.20.50.1-172.20.50.19"   # inside overlaySubnet

---
apiVersion: v1
kind: VtepNodeConfig
metadata:
  name: domain1-edge
spec:
  overlayRef: federation-net                # must match metadata.name above
  endpointRef: domain1-edge                 # must match an endpoints.name above
  vtepIP: 10.11.7.4                         # underlay IP of this VTEP
  addressPool: "172.20.50.20-172.20.50.49" # inside overlaySubnet

---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ros-network
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "vxlan200",
      "mode": "l2",
      "ipam": {
        "type": "static"
      }
    }

---

apiVersion: v1
kind: Pod
metadata:
  name: go1-navigation
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "ros-network", "ips": ["172.20.50.50/24"] }
    ]'
  labels:
    app: digital-twin-service
    node: go1-navigation
spec:
  containers:
    - name: go1-navigation
      tty: true
      image: dummy-ros-app
      imagePullPolicy: IfNotPresent
      env:
        - name: ROS_MASTER_URI
          value: "http://172.20.50.10:11311"
        - name: ROS_IP
          value: "172.20.50.50"
        - name: ROS_ROLE
          value: "subscriber"
---
