version: '3'
services:
  bootnode:
    image: dlt-node
    container_name: bootnode
    hostname: bootnode
    volumes:
      - ./../config/dlt/bootnode.env:/dlt-network/bootnode.env
      - ./../docker-images/dlt-node/scripts/password.txt:/dlt-network/password.txt
      - ./../docker-images/dlt-node/scripts/bootnode_start.sh:/dlt-network/bootnode_start.sh
    command: ./bootnode_start.sh
    network_mode: "host"

  node1:
    image: dlt-node
    container_name: node1
    hostname: node1
    depends_on:
      - bootnode
    volumes:
      - ./../config/dlt/node1.env:/dlt-network/node1.env
      - ./../docker-images/dlt-node/scripts/genesis_2_validators.json:/dlt-network/genesis.json
      - ./../docker-images/dlt-node/scripts/password.txt:/dlt-network/password.txt
      - ./../docker-images/dlt-node/scripts/node1_start.sh:/dlt-network/node1_start.sh      
    command: ./node1_start.sh
    network_mode: "host"

  eth-netstats:
    image: eth-netstats
    container_name: eth-netstats
    depends_on:
      - node1
    network_mode: "host"